# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    # Use active LTS release: https://github.com/nodejs/Release#release-schedule
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - 'node-v10-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'node-v10-{{ .Branch }}'
            - 'node-v10'

      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-v10-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Lint
          command: npm run lint:check

      - run:
          name: Format
          command: npm run format:check

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm test

      - run:
          name: Upload code coverage
          command: npm run codecov

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
